import { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: 'all', name: 'All Products', icon: '🛍️' },
  { id: 'electronics', name: 'Electronics', icon: '⚡' },
  { id: 'clothing', name: 'Clothing', icon: '👕' },
  { id: 'home', name: 'Home & Garden', icon: '🏠' },
  { id: 'sports', name: 'Sports', icon: '⚽' },
  { id: 'books', name: 'Books', icon: '📚' },
  { id: 'beauty', name: 'Beauty', icon: '✨' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium audio experience with active noise cancellation, 30-hour battery life, and comfortable over-ear design. Perfect for work and travel.',
    price: 249.99,
    originalPrice: 349.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 1283,
    inStock: true,
    tags: ['wireless', 'audio', 'noise-cancelling'],
  },
  {
    id: '2',
    name: 'Smart Fitness Tracker Watch',
    description: 'Track your health with heart rate monitoring, GPS, sleep analysis, and 7-day battery. Water resistant up to 50m.',
    price: 189.99,
    originalPrice: 229.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 876,
    inStock: true,
    tags: ['fitness', 'smartwatch', 'health'],
  },
  {
    id: '3',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit mechanical keyboard with tactile switches, anti-ghosting, and aluminum frame for competitive gaming.',
    price: 129.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 542,
    inStock: true,
    tags: ['gaming', 'keyboard', 'rgb'],
  },
  {
    id: '4',
    name: 'Portable Bluetooth Speaker',
    description: '360-degree surround sound, IPX7 waterproof, 24-hour playtime. Perfect companion for outdoor adventures.',
    price: 79.99,
    originalPrice: 99.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    rating: 4.4,
    reviewCount: 1024,
    inStock: false,
    tags: ['bluetooth', 'speaker', 'outdoor'],
  },
  {
    id: '5',
    name: 'Classic Comfort Hoodie',
    description: 'Soft fleece interior with relaxed fit. Available in multiple colors. Machine washable and fade-resistant.',
    price: 54.99,
    originalPrice: 69.99,
    category: 'clothing',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&h=400&fit=crop',
    rating: 4.3,
    reviewCount: 389,
    inStock: true,
    tags: ['hoodie', 'casual', 'comfortable'],
  },
  {
    id: '6',
    name: 'Premium Running Shoes',
    description: 'Lightweight mesh upper with responsive foam cushioning. Designed for long-distance running and everyday wear.',
    price: 119.99,
    originalPrice: 149.99,
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    rating: 4.8,
    reviewCount: 2156,
    inStock: true,
    tags: ['running', 'shoes', 'sports'],
  },
  {
    id: '7',
    name: 'Stainless Steel Water Bottle',
    description: 'Double-wall vacuum insulated, keeps drinks cold 24 hrs or hot 12 hrs. BPA-free and eco-friendly.',
    price: 34.99,
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 743,
    inStock: true,
    tags: ['hydration', 'eco', 'insulated'],
  },
  {
    id: '8',
    name: 'Minimalist Desk Lamp',
    description: 'Touch-sensitive dimming, USB charging port built-in, eye-care technology. Modern design for any workspace.',
    price: 49.99,
    originalPrice: 64.99,
    category: 'home',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 291,
    inStock: true,
    tags: ['lamp', 'desk', 'workspace'],
  },
  {
    id: '9',
    name: 'Organic Cotton Bed Sheets',
    description: '100% GOTS-certified organic cotton, 400 thread count, soft percale weave. Breathable and durable.',
    price: 89.99,
    originalPrice: 119.99,
    category: 'home',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 634,
    inStock: true,
    tags: ['organic', 'bedding', 'cotton'],
  },
  {
    id: '10',
    name: 'JavaScript: The Good Parts',
    description: 'A must-read for JavaScript developers. Learn the elegant, powerful features of the language from a master.',
    price: 24.99,
    category: 'books',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop',
    rating: 4.4,
    reviewCount: 1567,
    inStock: true,
    tags: ['javascript', 'programming', 'development'],
  },
  {
    id: '11',
    name: 'Vitamin C Brightening Serum',
    description: '15% Vitamin C with hyaluronic acid and niacinamide. Brightens skin, reduces dark spots, and evens skin tone.',
    price: 42.99,
    originalPrice: 55.99,
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 918,
    inStock: true,
    tags: ['skincare', 'vitamin-c', 'serum'],
  },
  {
    id: '12',
    name: 'Yoga Mat Premium',
    description: 'Eco-friendly TPE material, 6mm thick non-slip surface, alignment lines. Includes carrying strap.',
    price: 64.99,
    originalPrice: 79.99,
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1601925228843-84082df4e9cc?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 447,
    inStock: true,
    tags: ['yoga', 'fitness', 'eco'],
  },
  {
    id: '13',
    name: 'Slim Fit Chino Pants',
    description: 'Versatile slim fit chinos made from stretch cotton blend. Wrinkle-resistant for all-day comfort.',
    price: 59.99,
    category: 'clothing',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop',
    rating: 4.2,
    reviewCount: 223,
    inStock: true,
    tags: ['pants', 'chino', 'casual'],
  },
  {
    id: '14',
    name: 'Aromatherapy Diffuser',
    description: '500ml ultrasonic diffuser with 7 LED color options, auto shut-off, and whisper-quiet operation.',
    price: 39.99,
    originalPrice: 54.99,
    category: 'home',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop',
    rating: 4.4,
    reviewCount: 356,
    inStock: false,
    tags: ['aromatherapy', 'wellness', 'home'],
  },
  {
    id: '15',
    name: 'Wireless Charging Pad',
    description: '15W fast wireless charger compatible with all Qi-enabled devices. Sleek tempered glass surface.',
    price: 29.99,
    originalPrice: 39.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=400&fit=crop',
    rating: 4.3,
    reviewCount: 682,
    inStock: true,
    tags: ['wireless', 'charging', 'accessories'],
  },
  {
    id: '16',
    name: 'Natural Face Moisturizer',
    description: 'Lightweight daily moisturizer with SPF 30, hyaluronic acid, and green tea extract. Suitable for all skin types.',
    price: 32.99,
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 512,
    inStock: true,
    tags: ['moisturizer', 'spf', 'skincare'],
  },
];
